In [1]:
import numpy as np
import pandas as pd

In [2]:
housing=pd.read_csv("housing.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       505 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['CHAS'].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  505.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284451   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.703302   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
# %matplotlib inline

In [8]:
# import matplotlib.pyplot as plt

In [9]:
# housing.hist(bins=50, figsize=(20,15))

In [10]:
# import numpy as np
# def split(data, splitratio):
#     np.random.seed(42)
#     shuffle=np.random.permutation(len(data))
#     test_size=int(len(data)*splitratio)
#     test=shuffle[:test_size]
#     train=shuffle[test_size:]
#     print(train)
#     return data.iloc[test], data.iloc[train]

In [11]:
# test,train=split(housing, 0.2)

In [12]:
# print(len(test), len(train))

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
test,train=train_test_split(housing, test_size=0.2, random_state=42)

In [15]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train, test in split.split(housing, housing['CHAS']):
    test_data=housing.loc[test]
    train_data=housing.loc[train]

In [16]:
test_data['CHAS'].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [17]:
train_data['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [18]:
housing=train_data.copy()

In [19]:
corr=housing.corr()

In [20]:
corr['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680723
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [21]:
from pandas.plotting import scatter_matrix
# at=['MEDV', 'PTRATIO', 'ZN', 'LSTAT']
# scatter_matrix(housing[at], figsize=(12,8))

In [22]:
housing=train_data.drop('MEDV', axis=1)
housingla=train_data['MEDV'].copy()

In [23]:
housing.shape

(404, 13)

In [24]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  403.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279667   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.713853   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

There are mainly 3 types of objects in skikit learn
1. Estimators:- It estimates a parameter based on the data e.g. Imputer. It has fit method and transform method . Fit: fits in dataset and calculates internal parameters
2. Transformers:- transfomer takes input and returns output on the base of fit() it also has fit_transform() which fits and then transforms
3. Predictors:- LinerRegression is an example of predictors it has fit() and predict() functions in it. It also takes score() function which helps to evaluavate the score and accuracy of the output given by the predictors.

In [25]:
from sklearn.impute import SimpleImputer
im=SimpleImputer(strategy="median")
im.fit(housing)

SimpleImputer(strategy='median')

In [26]:
im.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.20900e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [27]:
x=im.transform(housing)

In [28]:
housing_tr=pd.DataFrame(x, columns=housing.columns)

In [29]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279493   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712975   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

for bringing the data at same scale we use scalers and helps us to analsys of the data easier for the ml model they are of two types:
standardscaler: it is (mean-value)/std this leads to reduce all values into a range from 0 to 1
Min max scaler: it (value-min)/(max-min) sklearn provides a class called MinMaxScaler this process is called normalization

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
pip=Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler()),
])

In [31]:
housing_tr=pip.fit_transform(housing)

In [32]:
housing_tr.shape

(404, 13)

In [33]:
housingla.shape

(404,)

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model=LinearRegression()
# model=DecisionTreeRegressor()
# model=RandomForestRegressor()
model.fit(housing_tr, housingla)

LinearRegression()

In [35]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  403.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279667   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.713853   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [36]:
housing_tr.shape

(404, 13)

In [37]:
housing.shape

(404, 13)

In [38]:
somedata=housing.iloc[:5]

In [39]:
samela=housingla.iloc[:5]
samela

254    21.9
348    24.5
476    16.7
321    23.1
326    23.0
Name: MEDV, dtype: float64

In [40]:
procesda=pip.fit_transform(somedata)

In [41]:
predict=model.predict(housing_tr)

In [42]:
from sklearn.metrics import mean_squared_error
mne=mean_squared_error(housingla, predict)
mne

23.31003536248901

In [43]:
from sklearn.model_selection import cross_val_score
scoring=cross_val_score(model, housing_tr, housingla, scoring="neg_mean_squared_error", cv=10)
scoring=-scoring
scoring

array([17.83525576, 18.13985003, 25.96772331, 14.64692028, 28.5048601 ,
       19.14232097, 55.90495016, 30.00711337, 17.23352189, 36.84956389])

In [44]:
def pr(scoring):
    print("scores:", scoring)
    print("mean:", scoring.mean())
    print("Standard Deviation:", scoring.std())

In [45]:
pr(scoring)

scores: [17.83525576 18.13985003 25.96772331 14.64692028 28.5048601  19.14232097
 55.90495016 30.00711337 17.23352189 36.84956389]
mean: 26.423207975133767
Standard Deviation: 11.890234143369446


In [46]:
from joblib import dump, load
dump(model, 'dragon.joblib')

['dragon.joblib']

In [47]:
test=test_data.drop('MEDV', axis=1)
testla=test_data['MEDV'].copy()
processed_test=pip.transform(test)

In [48]:
finalprediction=model.predict(processed_test)
finalmse=mean_squared_error(finalprediction, testla)
finalmse

1251.9694403782114

In [49]:
np.sqrt(finalmse)

35.383180190285486

In [50]:
processed_train=np.array(processed_test)
processed_test[3]

array([-0.51130008, -0.81649658,  1.10350733,  1.        ,  0.86453303,
       -0.05690275,  1.80268316, -1.02878854, -0.34015067, -0.60673678,
       -1.39707095, -0.42429609,  0.33470326])

In [51]:
from joblib import dump, load
model=load('dragon.joblib')

In [52]:
model.predict([[-0.51130008, -0.81649658,  1.10350733,  1.        ,  0.86453303,
       -0.05690275,  1.80268316, -1.02878854, -0.34015067, -0.60673678,
       -1.39707095, -0.42429609,  0.33470326]])

array([26.1221374])

In [53]:
predict=np.array(predict)

In [54]:
predict[3]

25.038210639008177